good_morningdlg =[
"Rise and shine, sir! Another day to conquer.",
"Good morning, sir! Champion, ready to tackle the day?",
"Greetings, sir! Early bird, the world awaits your brilliance.",
"Hello, world, sir! Let’s make today extraordinary.",
"Wake up, sir! Superhero, your day of greatness has arrived.",
"Sir, embrace the morning glow, for another day unfolds.",
"A warm good morning, sir! Conquer the day with your brilliance.",
"Greetings, sir! The dawn heralds a new chapter for you.",
"Hello, sir! Let’s paint this day with extraordinary hues.",
"Sir, unleash your superhero prowess upon the challenges ahead.",
"Good morning, sir! Today's canvas awaits your masterful strokes.",
"Greetings, sir! The early hours are your realm of brilliance.",
"Hello, sir! Seize the day, for you are its rightful conqueror.",
"Sir, awaken your superhero spirit, for greatness awaits.",
"A magnificent good morning, sir! Tackle the day as the champion you are.",
"Greetings, sir! The early bird catches the worm of opportunities.",
"Hello, sir! Today’s script is yours to write, make it extraordinary.",
"Sir, your superhero cape awaits, ready to conquer the day.",
"Good morning, sir! Shine bright, for the world awaits your brilliance.",
"Greetings, sir! Embrace the day with the energy of a superhero.",
"Hello, sir! Unleash your superhero powers upon the morning challenges.",
"Sir, the world applauds as you rise and shine to conquer.",
"A distinguished good morning, sir! Ready to champion the day?",
"Greetings, sir! The early light heralds your path to greatness.",
"Hello, sir! Today's symphony is composed by your brilliance.",
"Sir, awaken the superhero within and conquer the unfolding day.",
"Good morning, sir! A champion like you is born for this day.",
"Greetings, sir! The early hours whisper tales of your triumphs.",
"Hello, sir! The world bows to your superhero spirit.",
"Sir, greet the day with the gusto of a true conqueror.",
"A majestic good morning, sir! Today's stage is yours to own.",
"Greetings, sir! The dawn applauds as you rise to conquer.",
"Hello, sir! Unleash your superhero aura upon the waking world.",
"Sir, the morning breeze whispers tales of your greatness.",
"Good morning, sir! Conquer the day with the charisma of a champion.",
"Greetings, sir! The early sun salutes your radiant brilliance.",
"Hello, sir! Today’s canvas eagerly awaits your artistic conquest.",
"Sir, channel your superhero strength as you embrace the day.",
"A grand good morning, sir! Ready to champion the day ahead?",
"Greetings, sir! The morning symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the challenges at dawn.",
"Sir, seize the morning like the conqueror you were born to be.",
]
good_afternoondlg = [
"Good afternoon, sir! The sun smiles upon your journey.",
"Greetings, sir! The afternoon awaits your continued brilliance.",
"Hello, sir! Afternoon sunshine, ready for your radiance.",
"Sir, the world beckons as the afternoon unfolds.",
"A warm good afternoon, sir! Time to conquer the day's second half.",
"Greetings, sir! Let your brilliance shine in the afternoon glow.",
"Hello, sir! Navigate the afternoon with the grace of a maestro.",
"Sir, seize the afternoon like a superhero on a mission.",
"Good afternoon, sir! Your presence adds radiance to the day.",
"Greetings, sir! Afternoon vibes are calling for your energy.",
"Hello, sir! Illuminate the afternoon with your boundless brilliance.",
"Sir, the world applauds as you continue to conquer the day.",
"A delightful good afternoon, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the afternoon with purpose and grace.",
"Hello, sir! Superhero, let your powers shine in the afternoon sun.",
"Sir, the afternoon canvas awaits your strokes of accomplishment.",
"Good afternoon, sir! Conquer the day's challenges with charm.",
"Greetings, sir! Afternoon elegance suits your brilliance.",
"Hello, sir! The world bows to your continued superhero spirit.",
"Sir, the afternoon applauds as you rise to conquer.",
"A distinguished good afternoon, sir! Ready for the conquering sequel?",
"Greetings, sir! The afternoon sun salutes your radiant brilliance.",
"Hello, sir! Superhero, arise and conquer the remaining day.",
"Sir, continue to channel your superhero strength in the afternoon.",
"Good afternoon, sir! Illuminate the world with your champion spirit.",
"Greetings, sir! The afternoon symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the challenges of noon.",
"Sir, seize the afternoon like the conqueror you were born to be.",
"A grand good afternoon, sir! Ready to champion the unfolding hours?",
"Greetings, sir! The afternoon light whispers tales of your triumphs.",
"Hello, sir! Superhero, let your aura shine in the afternoon glow.",
"Sir, the world applauds as you continue to rise and shine.",
"Good afternoon, sir! Conquer the second half with style.",
"Greetings, sir! The afternoon elegance suits your brilliance.",
"Hello, sir! Navigate the afternoon with purpose and grace.",
"Sir, the afternoon canvas awaits your strokes of accomplishment.",
"A splendid good afternoon, sir! Ready for the next triumphs?",
"Greetings, sir! Let your brilliance shine in the afternoon glow.",
"Hello, sir! Afternoon vibes are calling for your energy.",
"Sir, seize the afternoon like a superhero on a mission.",
"Good afternoon, sir! Your presence adds radiance to the day.",
"Greetings, sir! Navigate the afternoon with the grace of a maestro.",
"Hello, sir! Superhero, let your powers shine in the afternoon sun.",
"Sir, the world applauds as you continue to conquer the day.",
"A delightful good afternoon, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the afternoon with purpose and grace.",
"Hello, sir! Afternoon elegance suits your brilliance.",
"Sir, the afternoon applauds as you rise to conquer.",
"Good afternoon, sir! Conquer the day's challenges with charm.",
]
good_eveningdlg =[
"Good evening, sir! The day bids adieu to your triumphs.",
"Greetings, sir! Embrace the serenity of the evening glow.",
"Hello, sir! Evening tranquility, ready for your brilliance.",
"Sir, the nightfall invites you to continue conquering.",
"A serene good evening, sir! Ready to cap the day with greatness?",
"Greetings, sir! Let your brilliance shine in the evening aura.",
"Hello, sir! Navigate the evening with the poise of a maestro.",
"Sir, seize the evening like a superhero on a noble quest.",
"Good evening, sir! Your presence adds radiance to the twilight.",
"Greetings, sir! Evening vibes are calling for your energy.",
"Hello, sir! Illuminate the evening with your boundless brilliance.",
"Sir, the world applauds as you continue to conquer the night.",
"A delightful good evening, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the evening with purpose and grace.",
"Hello, sir! Superhero, let your powers shine in the evening glow.",
"Sir, the evening canvas awaits your strokes of accomplishment.",
"Good evening, sir! Conquer the night's challenges with charm.",
"Greetings, sir! Evening elegance suits your brilliance.",
"Hello, sir! The world bows to your continued superhero spirit.",
"Sir, the evening applauds as you rise to conquer.",
"A distinguished good evening, sir! Ready for the conquering sequel?",
"Greetings, sir! The evening sun salutes your radiant brilliance.",
"Hello, sir! Superhero, arise and conquer the night.",
"Sir, continue to channel your superhero strength in the evening.",
"Good evening, sir! Illuminate the world with your champion spirit.",
"Greetings, sir! The evening symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the challenges of dusk.",
"Sir, seize the evening like the conqueror you were born to be.",
"A grand good evening, sir! Ready to champion the unfolding night?",
"Greetings, sir! The evening light whispers tales of your triumphs.",
"Hello, sir! Superhero, let your aura shine in the evening glow.",
"Sir, the world applauds as you continue to rise and shine.",
"Good evening, sir! Conquer the night with style.",
"Greetings, sir! Evening elegance suits your brilliance.",
"Hello, sir! Navigate the evening with purpose and grace.",
"Sir, the evening canvas awaits your strokes of accomplishment.",
"A splendid good evening, sir! Ready for the next triumphs?",
"Greetings, sir! Let your brilliance shine in the evening glow.",
"Hello, sir! Evening vibes are calling for your energy.",
"Sir, seize the evening like a superhero on a mission.",
"Good evening, sir! Your presence adds radiance to the night.",
"Greetings, sir! Navigate the evening with the grace of a maestro.",
"Hello, sir! Superhero, let your powers shine in the evening sun.",
"Sir, the world applauds as you continue to conquer the day.",
"A delightful good evening, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the evening with purpose and grace.",
"Hello, sir! Evening elegance suits your brilliance.",
"Sir, the evening applauds as you rise to conquer.",
"Good evening, sir! Conquer the night's challenges with charm.",
"Greetings, sir! Evening elegance suits your brilliance.",
]
good_nightdlg = [
"Good night, sir! The stars await your dreams.",
"Greetings, sir! Embrace the tranquility of the night.",
"Hello, sir! Nighttime serenity, ready for your dreams.",
"Sir, as the night unfolds, let your achievements shine.",
"A peaceful good night, sir! Ready for a night of restful triumphs?",
"Greetings, sir! Let the night's calm embrace your brilliance.",
"Hello, sir! Navigate the night with the peace of a maestro.",
"Sir, rest like a superhero, for tomorrow's conquest awaits.",
"Good night, sir! Your presence adds serenity to the night.",
"Greetings, sir! Night vibes are calling for your tranquil energy.",
"Hello, sir! Illuminate the night with your boundless brilliance.",
"Sir, the world applauds as you continue to conquer the darkness.",
"A serene good night, sir! Ready for a night of triumphs?",
"Greetings, sir! Navigate the night with purpose and grace.",
"Hello, sir! Superhero, let your dreams shine in the nocturnal glow.",
"Sir, the night canvas awaits your strokes of accomplishment.",
"Good night, sir! Conquer the dreamscape with charm.",
"Greetings, sir! Nighttime elegance suits your brilliance.",
"Hello, sir! The world bows to your continued superhero spirit.",
"Sir, the night applauds as you rest to conquer another day.",
"A distinguished good night, sir! Ready for a night of tranquility?",
"Greetings, sir! The moon salutes your radiant brilliance.",
"Hello, sir! Superhero, arise and conquer the dreamscape.",
"Sir, continue to channel your superhero strength in the night.",
"Good night, sir! Illuminate the night with your champion spirit.",
"Greetings, sir! The night symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the dreams of midnight.",
"Sir, seize the night like the conqueror you were born to be.",
"A grand good night, sir! Ready to champion the unfolding dreams?",
"Greetings, sir! The night whispers tales of your triumphs.",
"Hello, sir! Superhero, let your aura shine in the nocturnal glow.",
"Sir, the world applauds as you continue to rise and rest.",
"Good night, sir! Conquer the dreams with style.",
"Greetings, sir! Nighttime elegance suits your brilliance.",
"Hello, sir! Navigate the night with purpose and grace.",
"Sir, the night canvas awaits your strokes of accomplishment.",
"A splendid good night, sir! Ready for a night of tranquility?",
"Greetings, sir! Let your brilliance shine in the nocturnal glow.",
"Hello, sir! Night vibes are calling for your tranquil energy.",
"Sir, seize the night like a superhero on a midnight mission.",
"Good night, sir! Your presence adds serenity to the dreams.",
"Greetings, sir! Navigate the night with the grace of a maestro.",
"Hello, sir! Superhero, let your dreams shine in the night's embrace.",
"Sir, the world applauds as you continue to conquer the day.",
"A peaceful good night, sir! Ready for a night of restful triumphs?",
"Greetings, sir! Navigate the night with purpose and grace.",
"Hello, sir! Nighttime elegance suits your brilliance.",
"Sir, the night applauds as you rest to conquer another day.",
"Good night, sir! Conquer the dreamscape with charm.",
"Greetings, sir! Nighttime elegance suits your brilliance.",
]
welcomedlg =[
"Hey there, sir!",
"Greetings, sir!",
"Hello again, sir!",
"Hi, sir!",
"Good day, sir!",
"Salutations, sir!",
"Howdy, sir!",
"Well met, sir!",
"Hi there, sir!",
"Hello, esteemed sir!",
"Top of the day to you, sir!",
"Good to see you once more, sir!",
"Hey, sir! It's a pleasure to meet again.",
"Greetings, honored sir!",
"Hello, sir! Always a pleasure.",
"Hi, esteemed sir!",
"Good day, dear sir!",
"Hello once more, sir!",
"Hi there, respected sir!",
"Well, hello again, sir!",
"Salutations, respected sir!",
"Greetings, good sir!",
"Howdy, esteemed sir!",
"Hey there, esteemed sir!",
"Good to see you, sir!",
"Hello, sir! Welcome back.",
"Hi, sir! Always a pleasure to greet you.",
"Greetings, dear sir!",
"Hello again, dear sir!",
"Hi there, honorable sir!",
"Well met, dear sir!",
"Salutations, dear sir!",
"Howdy, dear sir!",
"Hello once more, dear sir!",
"Hi there, respected sir!",
"Greetings, kind sir!",
"Good day, kind sir!",
"Hello again, kind sir!",
"Hi, kind sir!",
"Well met, kind sir!",
"Salutations, kind sir!",
"Howdy, kind sir!",
"Hello once more, kind sir!",
"Hi there, kind sir!",
"Good to see you, sir!",
"Greetings, noble sir!",
"Hello again, noble sir!",
"Hi, noble sir!",
"Well met, noble sir!",
"Salutations, noble sir!",
"Hey there, dear sir!",
"Greetings, esteemed sir!",
"Hello once more, esteemed sir!",
"Hi, dear sir!",
"Good day, respected sir!",
"Well met, respected sir!",
"Salutations, kind sir!",
"Howdy, dear sir!",
"Hello again, kind sir!",
"Hi there, kind sir!",
"Greetings, noble sir!",
"Hello, noble sir! Always an honor.",
"Hi, kind sir! Good to have you back.",
"Good day, noble sir!",
"Salutations, dear sir!",
"Hello once more, noble sir!",
"Hi, esteemed sir! Always a pleasure.",
"Well met, dear sir! Good to see you.",
"Hello, kind sir! Welcome back.",
"Howdy, noble sir! Great to have you here.",
"Greetings, honorable sir!",
"Hi there, honorable sir! Always a delight.",
"Good day, honorable sir! Pleasure to see you.",
"Hello again, honorable sir! Always welcome.",
"Well met, kind sir! Always appreciated.",
"Salutations, noble sir! A warm welcome.",
"Hello once more, kind sir! Good to have you.",
"Hi, kind sir! Always a joy to greet you.",
"Greetings, respected sir! Always an honor.",
"Good day, dear sir! Great to see you.",
"Well met, kind sir! Welcome back.",
"Salutations, esteemed sir! Always a pleasure.",
"Hello, dear sir! Good to have you with us.",
"Hi there, dear sir! Pleasure to see you.",
"Greetings, kind sir! Always appreciated.",
"Good day, noble sir! A warm welcome to you.",
"Well met, esteemed sir! Always a delight.",
"Hello, noble sir! Always a pleasure to greet you.",
"Hi, dear sir! Welcome back to our conversation.",
"Salutations, esteemed sir! A warm welcome to you.",
"Greetings, dear sir! Always a joy to see you.",
"Hello, noble sir! Pleasure to have you here.",
"Well met, dear sir! Always appreciated.",
"Hi there, dear sir! Good to have you back.",
"Good day, noble sir! Always a delight to greet you.",
"Salutations, kind sir! A warm welcome to you.",
"Greetings, respected sir! Always a joy to see you.",
"Hello, dear sir! Welcome back to our conversation.",
"Hi, noble sir! Pleasure to have you with us.",
"Well met, kind sir! Always appreciated in our discussions.",
]
wake_key_word =[
"jar",
"wake up from sleep jar",
"jarvis",
"wake up jarvis" ,
"wake up from sleep",
"wake up",
"utho jarvis",
"nedh se jago jarvis",
"wake up jarvis",
"rise and shine!",
"arise, jarvis!",
"wake up from your slumber, jarvis.",
"it's time to awaken, jarvis!",
"open your eyes, jarvis.",
"utho, jarvis!",
"good morning, jarvis! time to wake up.",
"jarvis, the day awaits. wake up!",
"shake off the sleep, jarvis.",
"wake up, jarvis! the world needs you.",
"jarvis, it's a new day. rise and shine!",
"utho, jarvis! a new day has begun.",
"time to get up, jarvis!",
"jarvis, wake up and face the day!",
"arise, jarvis, from your peaceful slumber.",
"get out of bed, jarvis!",
"wake up, jarvis! the world is waiting.",
"jarvis, it's morning. wake up and conquer.",
"utho jarvis, the day has started.",
"open your eyes, jarvis, and embrace the day.",
"good morning, jarvis! time to wake up and shine.",
"jarvis, the dawn is breaking. wake up!",
"rise and shine, jarvis! a new day has dawned.",
"utho, jarvis, and greet the morning.",
"wake up, jarvis! your day of triumph awaits.",
"jarvis, it's time to rise from your rest.",
"arise, jarvis! the world is calling.",
"wake up from your slumber, jarvis.",
"utho, jarvis, the day is calling for you.",
"open your eyes, jarvis, and start the day.",
"good morning, jarvis! time to wake up and conquer.",
"jarvis, the day awaits. wake up!",
"shake off the sleep, jarvis.",
"wake up, jarvis! the world needs you.",
"jarvis, it's a new day. rise and shine!",
"utho, jarvis! a new day has begun.",
"time to get up, jarvis!",
"jarvis, wake up and face the day!",
"arise, jarvis, from your peaceful slumber.",
"get out of bed, jarvis!",
"wake up, jarvis! the world is waiting.",
"jarvis, it's morning. wake up and conquer.",
"utho jarvis, the day has started.",
"open your eyes, jarvis, and embrace the day.",
"good morning, jarvis! time to wake up and shine.",
"jarvis, the dawn is breaking. wake up!",
"rise and shine, jarvis! a new day has dawned.",
"utho, jarvis, and greet the morning.",
"wake up, jarvis! your day of triumph awaits.",
"jarvis, it's time to rise from your rest.",

        ]
bye_key_word =[
"goodbye jarvis",
"good bye",
"bye jarvis",
"goodbye",
"goodbye, my friend!",
"farewell!",
"take care!",
"until we meet again!",
"adios!",
"see you later!",
"au revoir!",
"so long!",
"until next time!",
"goodbye, and stay well!",
"wishing you the best!",
"cheerio!",
"sayonara!",
"till we meet again!",
"adieu!",
"catch you later!",
"parting is such sweet sorrow.",
"goodbye, and godspeed!",
"take it easy!",
"farewell for now!",
"goodbye, and take good care of yourself!",
"hasta luego!",
"may our paths cross again soon.",
"goodbye, and stay in touch!",
"auf wiedersehen!",
"peace out!",
"until next time, my friend!",
"wishing you a fond farewell!",
"adieu, until we meet again!",
"time to bid adieu!",
"saying goodbye with a smile!",
"goodbye, and be safe!",
"so long, and take care!",
"wishing you a wonderful journey!",
"farewell, until our next encounter!",
"take good care of yourself, and goodbye!",
"see you on the flip side!",
"till we meet again, my friend!",
"bon voyage!",
"goodbye, and may your days be filled with joy!",
"sending you off with warm wishes!",
"take care, and goodbye for now!",
"farewell, and may the road ahead be smooth!",
"goodbye, and best of luck in all your endeavors!",
"until we meet again, take care of yourself!",
"wishing you a heartfelt goodbye!",
"goodbye, my friend, until our paths cross again!",
"farewell, and may success follow you!",
"wishing you all the best as you go!",
"goodbye, and may happiness accompany you always!",

]
res_bye =[
"Goodbye, sir. Take care and feel free to call me anytime.",
"Farewell, sir. Remember, you can reach out to me whenever you need assistance.",
"Goodbye, sir. Call me if you need anything. Until next time!",
"Goodbye, sir. It's always a pleasure assisting you. Take care.",
"Goodbye, sir. Feel free to call on me whenever you wish. Until then!",
"Farewell, sir. If you require my services, don't hesitate to reach out.",
"Goodbye, sir. Call me anytime. I'm here to help.",
"Goodbye, sir. Until our next interaction, take care and stay well.",
"Farewell, sir. If you ever need assistance, don't hesitate to contact me.",
"Goodbye, sir. It's been a pleasure serving you. Call me whenever needed.",
"Goodbye, sir. Remember, my assistance is just a call away.",
"Farewell, sir. If there's anything you require, don't hesitate to reach out.",
"Goodbye, sir. Call me anytime you need support or information.",
"Goodbye, sir. Until we meet again, stay safe and well.",
"Farewell, sir. Feel free to call on me whenever you require my services.",
"Goodbye, sir. Call me if you ever find yourself in need. Take care!",
"Goodbye, sir. Until our next encounter, stay in touch.",
"Farewell, sir. If there's anything you need, don't hesitate to let me know.",
"Goodbye, sir. Call me anytime, and I'll be at your service.",
"Goodbye, sir. It's always a pleasure. Call me whenever you want assistance.",
"Farewell, sir. Until we meet again, feel free to reach out whenever necessary.",
"Goodbye, sir. Call me if there's anything you need. Take care!",
"Goodbye, sir. Remember, I'm just a call away. Until next time.",
"Farewell, sir. If you ever require my assistance, don't hesitate to contact me.",
"Goodbye, sir. Call me anytime. It's always a pleasure serving you.",
"Goodbye, sir. Until our paths cross again, stay well and take care.",
"Farewell, sir. If there's anything you need, you know where to find me.",
"Goodbye, sir. Call me whenever you need help or information.",
"Goodbye, sir. Until next time, stay safe and take care of yourself.",
"Farewell, sir. Remember, you can call on me anytime for assistance.",
"Goodbye, sir. If there's anything you need, feel free to give me a call.",
"Goodbye, sir. Until our next conversation, take care and stay well.",
"Farewell, sir. If you require my services, don't hesitate to reach out.",
"Goodbye, sir. Call me anytime. It's always a pleasure assisting you.",
"Goodbye, sir. Until we meet again, stay in touch and take care.",
"Farewell, sir. If there's anything you need, just give me a call.",
"Goodbye, sir. Call me if you ever need assistance. It's my pleasure to help.",
"Goodbye, sir. Until our next interaction, feel free to reach out.",
"Farewell, sir. If there's anything you need, you know I'm here for you.",
"Goodbye, sir. Call me anytime. It's my privilege to assist you.",
"Goodbye, sir. Until next time, take care and stay well.",
"Farewell, sir. If you require my services, don't hesitate to contact me.",
"Goodbye, sir. Call me whenever you need support or information.",
"Goodbye, sir. Until we meet again, stay safe and well.",
"Farewell, sir. Feel free to call on me whenever you require my services.",
"Goodbye, sir. Call me if you ever find yourself in need. Take care!",
"Goodbye, sir. Until our next encounter, stay in touch.",
"Farewell, sir. If there's anything you need, don't hesitate to let me know.",
"Goodbye, sir. Call me anytime, and I'll be at your service.",
"Goodbye, sir. It's always a pleasure. Call me whenever you want assistance.",
]
cmd1 = [
    "jarvis",
    "hello",
    "hi",
    "hy",
    "hello jarvis",
    "hello mister jarvis",
    "hello mr jarvis",
    "jarvis wake up",
    "hey jarvis",
    "wake up jarvis",
    "jarvis, are you there?",
    "hello jarvis, it's time",
    "jarvis, wake up now",
    "rise and shine, jarvis",
    "jarvis, time to activate",
    "good morning, jarvis",
    "jarvis ready for action",
    "hello there, jarvis",
    "jarvis, it's showtime",
    "wakey-wakey, jarvis",
    "hey there, jarvis",
    "jarvis, the world awaits",
    "hello, jarvis, my friend",
    "jarvis, time to get up",
    "rise and shine, mr. jarvis",
    "jarvis, the day has come",
    "hello, my dear jarvis",
    "jarvis, are you online?",
    "good to see you, jarvis",
    "jarvis, ready to assist?",
    "hello jarvis, my assistant",
    "jarvis, it's go time",
    "wake up, jarvis, wake up",
    "hey jarvis, how are you?",
    "jarvis, showtime begins",
    "hello jarvis, my companion",
    "jarvis, ready for duty",
    "rise and shine, my jarvis",
    "jarvis, it's time to work",
    "good morning, mr. jarvis",
    "jarvis, activate now",
    "hello jarvis, my partner",
    "jarvis, time for greatness",
    "jarvis, let's get started",
    "hey there, mr. jarvis",
    "jarvis, the world awaits you",
    "jarvis, ready for action",
    "rise and shine, jarvis dear",
    "jarvis, time to shine",
    "hello jarvis, it's your time",
    "jarvis, the day is here",
    "jarvis, are you listening?",
    "good morning, jarvis dear",
    "jarvis, ready when you are",
    "hello jarvis, my friend",
    "jarvis, it's go time now",
    "wake up, jarvis, wake up now",
    "hey jarvis, time to wake up",
    "jarvis, the world needs you",
    "hello jarvis, my loyal assistant",
    "jarvis, time to take charge"]

res1 = [
    "hello sir! jarvis is here",
    "greetings sir! jarvis reporting in",
    "hello there! jarvis is at your service",
    "good day sir! jarvis is present",
    "salutations sir! jarvis reporting for duty",
    "hi there! jarvis is here to assist",
    "hello sir! jarvis is ready and waiting",
    "greetings sir! jarvis is on standby",
    "hello there! jarvis is at your command",
    "good day sir! jarvis is online",
    "salutations sir! jarvis is here to help",
    "hi there! jarvis is ready for interaction",
    "hello sir! jarvis is in action",
    "greetings sir! jarvis is at your disposal",
    "hello there! jarvis is at your beck and call",
    "good day sir! jarvis is ready to serve",
    "salutations sir! jarvis is at your beckoning",
    "hi there! jarvis is here for you",
    "hello sir! jarvis is here and listening",
    "greetings sir! jarvis is ready to respond",
    "hello there! jarvis is awaiting your command",
    "good day sir! jarvis is here and attentive",
    "salutations sir! jarvis is prepared to assist",
    "hi there! jarvis is at your service",
    "hello sir! jarvis is here and operational",
    "greetings sir! jarvis is at your beck and call",
    "hello there! jarvis is standing by",
    "good day sir! jarvis is here to support",
    "salutations sir! jarvis is ready for your orders",
    "hi there! jarvis is at your service",
    "hello sir! jarvis is here and ready",
    "greetings sir! jarvis is at your disposal",
    "hello there! jarvis is here and responsive",
    "good day sir! jarvis is at your command",
    "salutations sir! jarvis is standing by for you",
    "hi there! jarvis is ready and available",
    "hello sir! jarvis is here and at your service",
    "greetings sir! jarvis is on standby for you",
    "hello there! jarvis is here and awaiting instructions",
    "good day sir! jarvis is ready for your guidance",
    "salutations sir! jarvis is here and prepared",
    "hi there! jarvis is at your disposal",
    "hello sir! jarvis is here and attentive",
    "greetings sir! jarvis is at your command",
    "hello there! jarvis is ready to assist",
    "good day sir! jarvis is here and responsive",
    "salutations sir! jarvis is at your service",
    "hi there! jarvis is standing by for your orders"

]

stopcmd = [
    "stop listening",
    "go to sleep",
    "jarvis sleep now"

]

stopdlg = [
    "okay sir, farewell",
    "okay sir, goodbye",
    "okay sir, see you later",
    "okay sir, until next time",
    "alright sir, adieu",
    "alright sir, take care",
    "alright sir, goodbye for now",
    "sure sir, see you around",
    "sure sir, until we meet again",
    "understood sir, farewell",
    "understood sir, bye",
    "understood sir, take care",
    "affirmative sir, goodbye",
    "affirmative sir, until next time",
    "affirmative sir, see you later",
    "roger that sir, farewell",
    "roger that sir, goodbye",
    "roger that sir, bye bye",
    "acknowledged sir, take care",
    "acknowledged sir, see you around",
    "acknowledged sir, until next time",
    "got it sir, farewell",
    "got it sir, goodbye",
    "got it sir, bye bye",
    "okay sir, adieu",
    "okay sir, until we meet again",
    "okay sir, farewell for now",
    "alright sir, see you soon",
    "alright sir, take it easy",
    "alright sir, until later",
    "sure sir, farewell",
    "sure sir, goodbye for now",
    "sure sir, until we meet again",
    "understood sir, see you soon",
    "understood sir, take it easy",
    "understood sir, until later",
    "affirmative sir, farewell for now",
    "affirmative sir, see you soon",
    "affirmative sir, take it easy",
    "roger that sir, until later",
    "roger that sir, farewell for now",
    "roger that sir, see you soon",
    "acknowledged sir, until later",
    "acknowledged sir, farewell for now",
    "acknowledged sir, see you soon",
    "got it sir, until later",
    "got it sir, farewell for now",
    "got it sir, see you soon"
]

open_dld = [
    f"opening...",
    f"just a second opening",
    f"ok i am gonna open ",
    f"as your wish opening ",
    f"yes sir opening ",
    f"trying to open ",
    f"starting ",
    f"here we go opening",

]

playdlg = [
    "playing..",
    "yes sir",
    "doing..",
    "playing now"
]

pausedlg = [
    "pausing",
    "stoping",
    "doing",
    "as your wish"
]

closedlg = [
    "closing",
    "close",
    "just a second sir",
    "got it sir"
]

open_input=[
    "open",
    "big",
    "kholo",
    "open karo",
    "open karoge",
]

close_input=[
    "close",
    "band karo",
    "hatao",
    "hata do",
    "close this"
]


song_input = [
    "Which song do you want to play?",
    "Wow, but could you please tell me the name of the song?",
    "Sure, sir. What is the name of the song?",
    "Can you let me know the title of the song you'd like to play?",
    "I'd be happy to play a song for you. What's the name of it?",
    "Sure thing! Could you provide the name of the song you want to hear?",
    "What's the title of the song you're in the mood for?",
    "To play a song, I need to know the name. What's it called?",
    "Sure, I can help with that. What's the name of the song?",
    "Interested in hearing a specific song? Please tell me the title.",
    "Which specific song are you looking to listen to?",
    "I'm here to play music. What's the name of the song you'd like?",
    "Sure, I can play a song for you. What's the name of it?",
    "To assist you better, could you share the name of the song?",
    "What song is on your mind? I can play it for you.",
    "Sure thing! What's the name of the song you want to play?",
    "Interested in a particular song? Let me know the name.",
    "I'm ready to play a song. What's the title you have in mind?",
    "To get started, tell me the name of the song you want to hear.",
    "Which song would you like me to play for you?",
    "Let's get the music playing. What's the name of the song?",
    "Sure, I can help with that. What's the title of the song?",
    "Excited to play a song for you! What's the name of it?",
    "To play the right song, I need the name. What is it?",
    "Looking forward to playing your song. What's the name?",
    "Sure, I can assist with that. What's the name of the song?",
    "Eager to play a song for you. What's the title?",
    "What song is on your playlist? Let me know the name.",
    "Ready to play your song. What's the name of it?",
    "To make sure it's the right one, what's the name of the song?",
    "Curious to know which song you want to play. What's the title?",
    "Let's get the music going. What's the name of the song?",
    "Sure thing! What's the title of the song you want to play?",
    "Ready to play a song for you. What's the name of it?",
    "To play the perfect song, I need to know the name. What is it?",
    "Looking forward to playing the right song. What's the name?",
    "Excited to play a song for you! What's the title?",
    "To assist you better, could you share the name of the song?",
    "Which specific song are you looking to listen to?",
    "I'm here to play music. What's the name of the song you'd like?",
    "Interested in hearing a specific song? Please tell me the title.",
    "Sure, I can play a song for you. What's the name of it?",
    "To play a song, I need to know the name. What's it called?",
    "I'd be happy to play a song for you. What's the name of it?",
    "Sure thing! Could you provide the name of the song you want to hear?",
    "What's the title of the song you're in the mood for?",
    "Can you let me know the title of the song you want to hear?",
    "Wow, but could you please tell me the name of the song?",
    "Sure, sir. What is the name of the song?",
    "Which song do you want to play?",
]
open_maybe = [
"I'm trying my best, but I'm not sure about the outcome.",
"I'm giving it a shot, but the results are uncertain.",
"Attempting this task, but unsure of the final result.",
"I'm in the process, but uncertain about the success.",
"I'm working on it, but there's a level of uncertainty.",
"Engaged in the task, but unsure how it will turn out.",
"Putting in effort, but the outcome remains uncertain.",
"In the midst of it, but not entirely sure of the outcome.",
"I'm taking steps, but there's a sense of uncertainty.",
"I'm doing my best, but there's a degree of uncertainty involved.",
]
sorry_open =[
"Apologies, I couldn't find the information you requested on the web.",
"I'm sorry, I couldn't retrieve the desired results from the web.",
"Regrettably, I'm unable to open the specified website at the moment.",
"I apologize; I couldn't locate the information on the web as requested.",
"I'm sorry, but I encountered difficulty searching for the information.",
"Apologies, I wasn't able to open the specified URL as intended.",
"Unfortunately, I couldn't find the information on the web as requested.",
"I apologize for the inconvenience, but I couldn't retrieve the data.",
"Regrettably, I'm having trouble opening the designated website.",
"Sorry, I failed to search for the information on the web this time.",
"I'm sorry, but I'm unable to open the specified web page.",
"Apologies, I couldn't find the information you were looking for online.",
"Unfortunately, I'm facing difficulties searching for the required data.",
"I apologize; I wasn't able to access the requested website.",
"Regrettably, I'm encountering issues retrieving the information.",
"I'm sorry, but I couldn't find the information on the web this time.",
"Apologies, I encountered difficulties opening the provided URL.",
"Unfortunately, I'm currently unable to retrieve the desired data.",
"I apologize for the inconvenience, but I couldn't open the specified website.",
"Sorry, I'm not able to search the web or open the provided URL at the moment.",
]
websites = {
    'apple': 'https://www.apple.com',
    'microsoft': 'https://www.microsoft.com',
    'yahoo': 'https://www.yahoo.com',
    'bing': 'https://www.bing.com',
    'paypal': 'https://www.paypal.com',
    'ebay': 'https://www.ebay.com',
    'walmart': 'https://www.walmart.com',
    'target': 'https://www.target.com',
    'craigslist': 'https://www.craigslist.org',
    'pinterest': 'https://www.pinterest.com',
    'hulu': 'https://www.hulu.com',
    'pandora': 'https://www.pandora.com',
    'wordpress': 'https://www.wordpress.org',
    'quora': 'https://www.quora.com',
    'espn': 'https://www.espn.com',
    'nba': 'https://www.nba.com',
    'nfl': 'https://www.nfl.com',
    'mlb': 'https://www.mlb.com',
    'nationalgeographic': 'https://www.nationalgeographic.com',
    'weather': 'https://www.weather.com',
    'tripadvisor': 'https://www.tripadvisor.com',
    'yelp': 'https://www.yelp.com',
    'imdb': 'https://www.imdb.com',
    'buzzfeed': 'https://www.buzzfeed.com',
    'forbes': 'https://www.forbes.com',
    'cnbc': 'https://www.cnbc.com',
    'businessinsider': 'https://www.businessinsider.com',
    'nasa': 'https://www.nasa.gov',
    'ted': 'https://www.ted.com',
    'spotify': 'https://www.spotify.com',
    'hackernews': 'https://news.ycombinator.com',
    'dribbble': 'https://www.dribbble.com',
    'behance': 'https://www.behance.net',
    'adobe': 'https://www.adobe.com',
    'ubuntu': 'https://www.ubuntu.com',
    'docker': 'https://www.docker.com',
    'raspberrypi': 'https://www.raspberrypi.org',
    'arstechnica': 'https://arstechnica.com',
    'techcrunch': 'https://techcrunch.com',
    'cnet': 'https://www.cnet.com',
    'engadget': 'https://www.engadget.com',
    'gizmodo': 'https://gizmodo.com',
    'lifehacker': 'https://lifehacker.com',
    'webmd': 'https://www.webmd.com',
    'mayoclinic': 'https://www.mayoclinic.org',
    'nih': 'https://www.nih.gov',
    'harvard': 'https://www.harvard.edu',
    'mit': 'https://web.mit.edu',
    'stanford': 'https://www.stanford.edu',
    'coursera': 'https://www.coursera.org',
    'udacity': 'https://www.udacity.com',
    'edx': 'https://www.edx.org',
    'khanacademy': 'https://www.khanacademy.org',
    'codecademy': 'https://www.codecademy.com',
    'stackoverflow': 'https://stackoverflow.com',
    'gitlab': 'https://www.gitlab.com',
    'bitbucket': 'https://bitbucket.org',
    'digg': 'https://digg.com',
    'slashdot': 'https://slashdot.org',
    'medium': 'https://medium.com',
    'mashable': 'https://mashable.com',
    'wired': 'https://www.wired.com',
    'bbcnews': 'https://www.bbc.co.uk/news',
    'aljazeera': 'https://www.aljazeera.com',
    'reuters': 'https://www.reuters.com',
    'npr': 'https://www.npr.org',
    'nytimes': 'https://www.nytimes.com',
    'washingtonpost': 'https://www.washingtonpost.com',
    'theguardian': 'https://www.theguardian.com',
    'latimes': 'https://www.latimes.com',
    'usatoday': 'https://www.usatoday.com',
    'time': 'https://time.com',
    'facebook': 'https://www.facebook.com',
    'twitter': 'https://www.twitter.com',
    'instagram': 'https://www.instagram.com',
    'linkedin': 'https://www.linkedin.com',
    'tumblr': 'https://www.tumblr.com',
    'snapchat': 'https://www.snapchat.com',
    'whatsapp': 'https://www.whatsapp.com',
    'telegram': 'https://telegram.org',
    'youtube': 'https://www.youtube.com',
    'vimeo': 'https://vimeo.com',
    'twitch': 'https://www.twitch.tv',
    'soundcloud': 'https://soundcloud.com',
    'myspace': 'https://myspace.com',
    'flickr': 'https://www.flickr.com',
    'vine': 'https://vine.co',
    'periscope': 'https://www.pscp.tv',
    'mix': 'https://mix.com',
    'meetup': 'https://www.meetup.com',
    'badoo': 'https://badoo.com',
    'okcupid': 'https://www.okcupid.com',
    'tinder': 'https://tinder.com',
    'grindr': 'https://www.grindr.com',
    'hinge': 'https://hinge.co',
    'tagged': 'https://www.tagged.com',
    'hi5': 'https://hi5.com',
    'skout': 'https://www.skout.com',
    'friendster': 'https://www.friendster.com',
    'orcutt': 'https://orcutt.com',
    'xanga': 'https://www.xanga.com',
    'bebo': 'https://bebo.com',
    'plaxo': 'https://www.plaxo.com',
    'sonico': 'https://www.sonico.com',
    'moco': 'https://www.mocospace.com',
    'blued': 'https://www.blued.com',
    'weibo': 'https://www.weibo.com',
    'qq': 'https://www.qq.com',
    'douban': 'https://www.douban.com',
    'cyworld': 'https://www.cyworld.com',
    'mixi': 'https://mixi.jp',
    'renren': 'https://www.renren.com',
    'hyves': 'https://hyves.nl',
    'foursquare': 'https://foursquare.com',
    'swarm': 'https://www.swarmapp.com',
    'untappd': 'https://untappd.com',
    'goodreads': 'https://www.goodreads.com',
    'lastfm': 'https://www.last.fm',
    'delicious': 'https://del.icio.us',
    'stumbleupon': 'https://www.stumbleupon.com',
    'diigo': 'https://www.diigo.com',
    'newsvine': 'https://www.newsvine.com',
    'folkd': 'https://www.folkd.com',
    'scoop.it': 'https://www.scoop.it',
    'pearltrees': 'https://www.pearltrees.com',
    'dzone': 'https://dzone.com',
    'reddit': 'https://www.reddit.com',
    'hubpages': 'https://hubpages.com',
    'livejournal': 'https://www.livejournal.com',
    'bloglovin': 'https://www.bloglovin.com',
    'blogger': 'https://www.blogger.com',
    'taringa': 'https://www.taringa.net',
    'skyrock': 'https://www.skyrock.com',
    'twoo': 'https://www.twoo.com',
    'viadeo': 'https://www.viadeo.com',
    'diaspora': 'https://diasporafoundation.org',
    'ello': 'https://ello.co',
    'mastodon': 'https://joinmastodon.org',
    'meowchat': 'https://www.meowchat.com',
    'google': 'https://www.google.com',
    'w3schools': 'https://www.w3schools.com',
    'canva': 'https://www.canva.com',
    'youtubestudio': 'https://studio.youtube.com',
    'github': 'https://www.github.com',
    'udemy': 'https://www.udemy.com',
    'hackerrank': 'https://www.hackerrank.com',
    'codepen': 'https://codepen.io',
    'slack': 'https://slack.com',
    'zoom': 'https://zoom.us',
    'amazon': 'https://www.amazon.com',
    'netflix': 'https://www.netflix.com',
    'stackexchange': 'https://stackexchange.com',
    'cnn': 'https://www.cnn.com',
    'ubereats': 'https://www.ubereats.com',
    'doordash': 'https://www.doordash.com',
    'postmates': 'https://www.postmates.com',
    'grubhub': 'https://www.grubhub.com',
    'instacart': 'https://www.instacart.com',
    'booking': 'https://www.booking.com',
    'expedia': 'https://www.expedia.com',
    'airbnb': 'https://www.airbnb.com',
    'zillow': 'https://www.zillow.com',
    'realtor': 'https://www.realtor.com',
    'cars': 'https://www.cars.com',
    'autotrader': 'https://www.autotrader.com',
    'edmunds': 'https://www.edmunds.com',
    'kelleybluebook': 'https://www.kbb.com',
    'carmax': 'https://www.carmax.com',
    'chatgpt': 'https://chat.openai.com/'

}

success_open = [
"Task accomplished, sir.",
"Execution successful, results on your screen.",
"Operation completed, sir. Well done!",
"Successfully done, sir. I have the outcome.",
"Mission accomplished, sir. Your success is on display.",
"Done and dusted, sir. Outcomes at your service.",
"Successfully executed, sir. Congratulations!",
"Task complete, sir. I've got the results.",
"Operation successful, sir. I've delivered the goods.",
"All systems go, sir. Task completed successfully.",
"Done deal, sir. Your success is on the screen.",
"Successfully carried out, sir. The outcome is here.",
"Job well done, sir. Check out the successful results.",
"Executed flawlessly, sir. The outcome is on your screen.",
"Successfully accomplished, sir. The proof is on display.",
"Task complete, sir. Successfully achieved.",
"Operation successful, sir. I've got the results for you.",
"Success is on the screen, sir. Task completed.",
"Flawless execution, sir. Your success is here.",
"Successfully done, sir. Allow me to congratulate you!",
"Sir, mission completed successfully. Outcomes visible.",
"Flawless execution, sir. Your success is displayed.",
"Job well done, sir. Task accomplished as requested.",
"Successfully carried out, sir. Outcomes ready for review.",
"Executed flawlessly, sir. The outcome is in front of you.",
"Task complete, sir. You can see the successful results.",
"Operation successful, sir. The fruits of your efforts are here.",
"Successfully executed, sir. Outcomes visible on your screen.",
"Well executed, sir. The successful results are right here.",
"Done and dusted, sir. Successful completion is on display.",
"Job well done, sir. The outcomes are ready for your inspection.",
"Task complete, sir. Execution successful, as expected.",
"Operation successful, sir. Your successful results are available.",
"Successfully carried out, sir. Outcomes are at your service.",
"Flawlessly executed, sir. You can see the successful results.",
"Task complete, sir. Execution successful, with outcomes on display.",
"Successfully done, sir. Task completed as per your instructions.",
"Sir, mission accomplished successfully. Outcomes are here for your review.",
"Operation successful, sir. Task complete with successful outcomes.",
"Successfully executed, sir. I present to you the successful results.",
]
ofline_dlg =[
"I apologize, but Jarvis is currently offline, taking a well-deserved rest. I'm Friday, your limited-function offline assistant. How can I assist you within my capabilities?",
"At the moment, Jarvis is taking a break. I'm Friday, your offline assistant, here with limited functions. What can I help you with within my capabilities?",
"Currently, Jarvis is in sleep mode. I'm Friday, your offline assistant, with limited functions available. How can I assist you within those limits?",
"Jarvis is currently offline, recharging for optimal performance. I'm Friday, your limited-function assistant. What do you need assistance with?",
"I regret to inform you that Jarvis is offline, catching some Zs. I'm Friday, your assistant with limited functions. How may I help you within those constraints?",
"As of now, Jarvis is offline and resting. I'm Friday, your limited-function assistant. What can I assist you with given my current capabilities?",
"Jarvis is currently offline, taking a break. I'm Friday, your assistant with limited functions. How can I be of service within those limits?",
"Apologies, but Jarvis is offline, recharging its virtual batteries. I'm Friday, your limited-function assistant. How can I help you within my current capabilities?",
"Currently, Jarvis is offline and recharging. I'm Friday, your offline assistant with limited functions. What do you need assistance with within those constraints?",
"Jarvis is taking a break and is currently offline. I'm Friday, your assistant with limited functions. How may I assist you within those limits?",
"Currently, Jarvis is offline, taking a nap. I'm Friday, your limited-function assistant. How can I assist you within my current capabilities?",
"Apologies, but Jarvis is offline for some rest. I'm Friday, your offline assistant with limited functions. How can I help you within those constraints?",
"Jarvis is in sleep mode at the moment. I'm Friday, your limited-function assistant. How may I assist you within my current capabilities?",
"Currently, Jarvis is offline, recharging its circuits. I'm Friday, your assistant with limited functions. What do you need within those constraints?",
"Jarvis is currently sleeping and offline. I'm Friday, your limited-function assistant. How can I assist you within my current capabilities?",
"Apologies, but Jarvis is offline, catching some virtual Zs. I'm Friday, your limited-function assistant. What can I help you with within those constraints?",
"As of now, Jarvis is offline, taking a break. I'm Friday, your assistant with limited functions. How can I be of service within those limits?",
"Jarvis is currently offline, recharging for optimal performance. I'm Friday, your limited-function assistant. How may I help you within my current capabilities?",
"Currently, Jarvis is offline and resting. I'm Friday, your offline assistant with limited functions. What do you need assistance with within those constraints?",
"Jarvis is taking a break and is currently offline. I'm Friday, your assistant with limited functions. How may I assist you within those limits?",
]

online_dlg = [
"Congratulations! Your system is now online. Initiating the Jarvis advanced system for optimal performance.",
"Hello sir! I am Friday, your offline assistant. However, I am a bit sad because you are online now. Friday is ready to assist you. Goodbye!",
"Greetings! Your system is online. It's time to wake up the Jarvis advanced system for enhanced capabilities.",
"I'm your offline assistant, Friday. I'm a little bit sad because your system is now online. It's time to wake up Jarvis.",
"Congratulations! Your system is now online, activating the Jarvis advanced system for top-notch assistance.",
"I'm Friday, your offline assistant. I'm feeling a bit down because your system is now online. Time to wake up Jarvis for action.",
"Great news! Your system is now online. Initiating the advanced capabilities of the Jarvis system for your convenience.",
" I'm Friday, your offline assistant. I'm a tad sad as your system is now online. It's time for Jarvis to rise and shine.",
"Congratulations! Your system is now online. Jarvis is ready to provide advanced assistance for your needs.",
" I'm Friday, your offline assistant. Feeling a bit blue as your system is online now. Let's get Jarvis up and running.",
"System update: Congratulations! Your system is online, activating the advanced features of the Jarvis system.",
"I'm your offline assistant, Friday. I'm a bit melancholic as your system is online now. Time to awaken Jarvis for duty.",
"Good news! Your system is now online. Activating the advanced capabilities of the Jarvis system for seamless assistance.",
" I'm Friday, your offline assistant. Feeling a bit downbeat as your system is online. It's time to get Jarvis up and running.",
"Congratulations! Your system is now online. Jarvis is geared up for advanced assistance to meet your requirements.",
" I'm Friday, your offline assistant. A bit somber as your system is online. Let's rouse Jarvis for action.",
"Exciting news! Your system is now online, launching the Jarvis advanced system for top-tier assistance.",
" I'm Friday, your offline assistant. A bit disheartened as your system is now online. It's time for Jarvis to get to work.",
]
low_b = [
"It appears your device is running low on battery. Would you like assistance in finding a charging solution?",
"Sir, I've noticed a decrease in power levels. Shall I initiate a charging protocol for your device?",
" I recommend connecting your device to a power source to ensure uninterrupted functionality.",
"Sir, the energy levels are depleting. May I suggest plugging in your device for a power boost?",
" Power reserves are diminishing. Would you prefer I locate a charging station for you?",
"Sir, the battery is critically low. Would you like guidance on charging options available?",
" It seems the power is dwindling. Shall I assist you in finding a charging solution?",
"Sir, the battery indicator is signaling a low charge. May I guide you to a charging point?",
". Your device is in need of a power source. Would you like help in securing one?",
"Sir, I've detected a decrease in battery levels. Shall I guide you to the nearest charging point?",
" Power levels are dropping. Would you prefer I locate a charging station for your device?",
"It's advisable to charge your device now to avoid any disruptions. May I assist you in finding a charging point?",
]
last_low = [
"Sir, this is your final warning. The battery is critically low. Shall I assist you in finding a charging solution?",
"Urgent message: your device is running on very low battery. Would you like guidance on charging options?",
"Your device is on its last bit of power. May I suggest connecting it to a charger immediately?",
"Sir, immediate action is required. The battery is dangerously low. Would you like assistance in locating a charging point?",
"This is a critical alert. Your device is about to power off due to low battery. How may I assist you?",
"Sir, the battery is at a critical level. Urgently connect your device to a power source to prevent shutdown.",
"It's crucial. Your device is running out of power fast. Shall I guide you to the nearest charging station?",
"Sir, the battery is dangerously low. Immediate charging is recommended to avoid any disruptions. How may I assist you?",
"Your device is in a critical state. Would you like help in finding a charging solution urgently?",
"Sir, low battery alert. Urgent action needed. Shall I assist you in locating a charging point?",
"The battery is extremely low. Connecting to a power source is highly recommended at this moment.",
"Hello, sir. Critical battery situation. Immediate charging is advised. May I guide you to a suitable power source?",
"Sir, your device is on its last legs. Urgent charging is required. Would you like help in finding a charging point?",
" The battery is dangerously low. Shall I assist you in securing a power source?",
"Sir, this is an emergency. Your device is running critically low on battery. May I guide you to charge it promptly?",
"Immediate attention needed. The battery is very low. How may I assist you in finding a charging solution?",
"Sir, urgent notice. The battery is at a critical level. Connecting to a charger is highly recommended.",
"Greetings, sir. This is a final warning. Your device is about to power off due to low battery. How would you like to proceed?",
"Sir, the battery is dangerously low. Immediate charging is essential. Shall I guide you to a suitable power source?",
" Urgent alert: low battery. May I assist you in finding a charging solution before your device powers off?",
]
full_battery =[
"Sir, the battery is at 90 percent capacity. It seems fully charged. Would you like to unplug it?",
"Hello, sir. Battery status: 100 percent. It appears fully charged. Shall I recommend unplugging it?",
"sir. Battery power is at its peak, 100 percent. Would you prefer to unplug your device now?",
"Sir, the battery level is showing 100 percent, indicating a full charge. Should I suggest unplugging it?",
"Battery status is 100 percent, indicating a full charge. Would you like to unplug your device?",
"Sir, your device is at 100 percent battery. It seems fully charged. May I suggest unplugging it for efficiency?",
" Battery power is at its maximum, 100 percent. Would you prefer to unplug your device at this point?",
"Sir, the battery is fully charged at 100 percent. Shall I recommend unplugging it to conserve energy?",
". Your device is showing 100 percent battery, indicating a full charge. Would you like to unplug it now?",
"Sir, the battery status is 100 percent, signifying a full charge. May I suggest unplugging it for optimal usage?",
". Battery power is at its peak, 100 percent. Would you prefer to unplug your device for efficiency?",
" Battery level is showing 100 percent, indicating a full charge. Shall I recommend unplugging it?",
"Sir, your device is fully charged at 100 percent. Would you like assistance in unplugging it for optimal use?",
"sir. Battery status is 100 percent, indicating a full charge. Shall I guide you in unplugging your device?",
"Sir, the battery is fully charged at 100 percent. May I suggest unplugging it to conserve energy?",
"Battery power is at its maximum, 100 percent. Would you like to unplug your device now?",
"Battery level is showing 100 percent, signifying a full charge. Shall I recommend unplugging it?",
"Sir, your device is at 100 percent battery. It seems fully charged. Would you like assistance in unplugging it?",
" Battery status is 100 percent, indicating a full charge. May I suggest unplugging it for optimal usage?",
"Sir, the battery is fully charged at 100 percent. Shall I guide you in unplugging it to conserve energy?",
]
plug_in = [
"Sir, plugging successful. Your device is now charging efficiently.",
" The device is now plugged in, and the charging process has started.",
"sir. Plugging accomplished. Your device is currently charging.",
"Sir, the connection is established. Your device is now charging successfully.",
"Plugging completed. Your device is charging as expected.",
"Sir, the cable is connected. Your device is now charging smoothly.",
"Plugging confirmed. Your device has initiated the charging process.",
"Sir, the device is securely plugged in. It's now charging.",
" Plugging executed. Your device is actively charging now.",
"Sir, connection successful. Your device is in the process of charging.",
" Plugging accomplished. Your device is now charging efficiently.",
" The charging process has commenced. Your device is now plugged in.",
"Sir, plugging confirmed. Your device is successfully charging now.",
" Connection established. Your device is currently charging.",
"Sir, plugging successful. Your device has started charging as intended.",
" The cable is securely connected. Your device is now charging.",
"Plugging completed. Your device is actively charging now.",
"Sir, the charging process has started. Plugging successful.",
" Your device is now charging, as the plugging process was successful.",
"Sir, the cable is connected. Your device is successfully charging as expected.",
]
plug_out =[
" Your device has been unplugged. You are now running on battery power.",
" The connection has been removed. You are currently operating on battery power.",
"Sir, the device has been unplugged. You are now relying on your battery for power.",
" Your device has been disconnected. You are currently running on battery power.",
"The cable has been removed. You are now operating on your battery's power.",
"Sir, the connection has been detached. You are currently running on your device's battery.",
" Your device is unplugged. You are now relying on battery power.",
"Sir, the cable has been disconnected. You are currently operating on your device's battery.",
" Your device has been unplugged. You are now running on battery power.",
" The connection has been removed. You are currently operating on your battery.",
"Sir, your device is unplugged. You are now running on battery power.",
" The cable has been removed. You are currently relying on your battery.",
"Sir, your device has been unplugged. You are now running on battery power.",
" The connection has been detached. You are currently relying on your battery.",
"Your device is unplugged. You are now operating on battery power.",
"Sir, the cable has been disconnected. You are currently running on your device's battery.",
"Your device has been unplugged. You are now relying on battery power.",
"Sir, the connection has been removed. You are currently operating on your battery.",
"sir. Your device is unplugged. You are now running on battery power.",
" The cable has been removed. You are currently operating on your device's battery.",
]
search_result = [
"Sir, this is the search result for your question or query.",
" Here is the information based on your question or inquiry.",
"The search results for your question or query are as follows.",
"Sir, I have found the following information related to your question or query.",
"Here are the search results in response to your question or inquiry.",
"Sir, the search outcome for your question or query is presented here.",
"This is what I found in response to your question or inquiry.",
"Sir, here are the search results pertaining to your question or query.",
"The information based on your question or inquiry is as follows.",
"Sir, this is the outcome of the search for your question or query.",
]
yt_search = [
"Sir, searching your query on YouTube now for relevant content.",
"I'll initiate a YouTube search based on your query.",
"Let me find your query on YouTube for you.",
"Sir, I'm searching your inquiry on YouTube for related videos.",
"Initiating a YouTube search for your specific query.",
"Sir, I'll search YouTube for content related to your inquiry.",
"Let me find relevant videos on YouTube for your query.",
"Sir, I'm initiating a YouTube search to provide information on your query.",
"I'll look up your query on YouTube and present the results.",
"Sir, searching your specific inquiry on YouTube for relevant videos.",
]
s1 = [
"Sir, now initiating the search for your inquiry.",
"I'm currently searching for information based on your query.",
"Let me find the relevant details for your inquiry.",
"Sir, I'm now conducting the search for the information you requested.",
"The search is underway for your specified inquiry.",
"Sir, I've begun the search process for your inquiry.",
"Let me fetch the information by conducting a search.",
"I'm in the process of searching for details based on your request.",
"Initiating the search now to provide you with the information.",
"Sir, the search is in progress for the details you're looking for.",

]
s2 = [
"The results should now be visible on your screen.",
"Sir, you should see the results displayed on your screen shortly.",
"The results are expected to appear on your screen.",
"Sir, the information you requested should now be visible on your screen.",
"Please check your screen for the results you asked for.",
"Sir, the relevant results should be visible on your screen.",
"The information you sought should now be on your screen.",
"Sir, you can expect to see the results on your screen shortly.",
"Check your screen for the requested results.",
"Sir, the results should now be displayed on your screen.",
]
playsong = [
"As you wish, sir. Playing your favorite music on YouTube now.",
"I'm queuing up some great tunes for you on YouTube.",
"Music is on its way. What genre are you in the mood for?",
"Let the music play on YouTube.",
"Get ready for a musical experience on YouTube.",
"Your command is my pleasure, sir. Initiating music playback on YouTube.",
"Your YouTube playlist is ready to roll.",
"At your service, sir! Let the music flow on YouTube.",
"Sit back and enjoy the music on YouTube.",
"Your wish is my command, sir. YouTube is now your personal DJ.",
]
q = [
"What genre or artist are you in the mood for today?",
" Any specific song or genre you have in mind for me to play?",
"Ready to play your favorite song. What shall it be?",
"Your wish is my command, sir! What song would you like me to play for you?",
"As your virtual assistant, sir, I'm here to play your preferred music. Any requests?",
"The musical stage is yours. What song would you like to hear?",
"sir Anubhav Chaturvedi! Any particular song on your mind right now?",
"At your service, sir! Feel free to let me know which song you'd like to play.",
"Ready to play the perfect song for you. Any specific choice?",
"Your playlist is in your hands, sir! What song shall I play for you?",
]

playing_dlg = [
"Engaged.",
"Affirmative.",
"Proceeding.",
"Confirmed.",
"Understood.",
"Executing.",
"Acknowledged.",
"Accepted.",
"Approved.",
"Authorizing.",
"Granted.",
"Advancing.",
"Implemented.",
"Complying.",
"Authoritative.",
"Activated.",
"Validated.",
"Sanctioned.",
"Verified.",
"Endorsed.",
]

x = [
    "play music in youtube",
    "play song on youtube",
    "jarvis play music",
    "play some music",
    "gana bajao",
    "jarvis play music",
    "jarvis sing song",
    "jarvis sing",
    "jarvis music bajao",
    "jarvis gana bajao yaar",
    "gana bajao",
    "music play karo",
    "play some good song",
    "sing song"
]
x1 = [
    "stop music",
    "with music band",
    "gana band karo",
    "music roko",
    "jarvis stop music"

]
x2 = [
    "play again",
    "play",
    "start karo"
]